spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_example?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    org:
      springframework:
        web: debug
    mybatis:
      plus:
        demo:
          user: debug