server:
  port: 9090

spring:
  security:
    dynamic:
      no-matcher-permit: false
      authority-key: dynamic-demo
      permits:
        - /hello
        - /error
  redis:
    host: 192.168.199.129
logging:
  level:
    org:
      springframework:
        web: debug
        security: debug